# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdbcrawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genres',
            field=models.ManyToManyField(db_table=b'movies_genres', to='imdbcrawler.Movie'),
        ),
    ]
