# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdbcrawler', '0003_auto_20170314_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.TextField(),
        ),
    ]
