# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdbcrawler', '0004_auto_20170315_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=767),
        ),
    ]
