# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdbcrawler', '0007_auto_20170316_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='votes',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
